@base = http://localhost:5208

GET {{com.project.pagapoco.app.webapi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{base}}/api/User/list
Accept: application/json

###

#GET {{base}}/api/User/
#Accept: application/json

###

GET {{base}}/api/User?pageIndex=1&pageSize=5
Accept: application/json

###

GET {{base}}/api/User
Accept: application/json

###