@base = http://localhost:5208

GET {{base}}/api/users
Accept: application/json

###

GET {{base}}/api/users?pageIndex=1&pageSize=5
Accept: application/json

###

GET {{base}}/api/users/67890123
Accept: application/json

###

#GET {{base}}/api/users/list
#Accept: application/json

###