@base = http://localhost:5208

GET {{base}}/api/User
Accept: application/json

###

GET {{base}}/api/User?pageIndex=1&pageSize=5
Accept: application/json

###

GET {{base}}/api/User/12345678
Accept: application/json

###

POST {{base}}/api/User
Content-Type: application/json

{
    "dni": 22998822,
    "firstname": "Jose",
    "lastname": "Gomez",
    "email": "micorreojose@gmail.com",
    "password": "123456"
}

###

#GET {{base}}/api/users/list
#Accept: application/json

###